name: PR Title Lint

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  lint-pr-title:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        with:
          types: |
            feat
            fix
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
