# .github/workflows/release-please.yml
name: Release Please

on:
  workflow_dispatch:

jobs:
  release-please:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: simple
          package-name: your-project-name
          token: ${{ secrets.GITHUB_TOKEN }}
          changelog-types: >
            [
              {"type":"feat","section":"Features","hidden":false},
              {"type":"fix","section":"Bug Fixes","hidden":false},
              {"type":"chore","section":"Chores","hidden":true},
              {"type":"docs","section":"Documentation","hidden":false},
              {"type":"style","section":"Styles","hidden":true},
              {"type":"refactor","section":"Code Refactoring","hidden":false},
              {"type":"perf","section":"Performance","hidden":false},
              {"type":"test","section":"Tests","hidden":true},
              {"type":"build","section":"Build System","hidden":true},
              {"type":"ci","section":"CI/CD","hidden":true},
              {"type":"revert","section":"Reverts","hidden":false}
            ]
          # This creates a PR but only releases when tag is pushed
          releases-only: true
